#[wokwi]
#version = 1
#firmware = '.pio/build/lilygo-t-display-s3/firmware.bin'
#elf = '.pio/build/lilygo-t-display-s3/firmware.elf'


[wokwi]
version = 1
firmware = ".pio/build/esp32-s3-devkitc-1/firmware.bin"
elf = ".pio/build/esp32-s3-devkitc-1/firmware.elf"